/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#141b2b",
        "tertiary-fixed": "#ffdbcd",
        "on-secondary-container": "#006172",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#ffede6",
        "surface-container-low": "#f1f3ff",
        "on-background": "#141b2b",
        "secondary": "#00687a",
        "primary-fixed": "#dbe1ff",
        "primary": "#004ac6",
        "on-primary-container": "#eeefff",
        "inverse-primary": "#b4c5ff",
        "on-tertiary-fixed": "#360f00",
        "outline-variant": "#c3c6d7",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f9f9ff",
        "secondary-fixed-dim": "#4cd7f6",
        "on-primary-fixed-variant": "#003ea8",
        "background": "#f9f9ff",
        "surface-container-high": "#e1e8fd",
        "surface-variant": "#dce2f7",
        "on-secondary-fixed": "#001f26",
        "secondary-fixed": "#acedff",
        "surface-dim": "#d3daef",
        "error": "#ba1a1a",
        "inverse-on-surface": "#edf0ff",
        "tertiary": "#943700",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#b4c5ff",
        "on-tertiary-fixed-variant": "#7d2d00",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#dce2f7",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#434655",
        "on-error": "#ffffff",
        "surface-container": "#e9edff",
        "surface-tint": "#0053db",
        "primary-container": "#2563eb",
        "surface": "#f9f9ff",
        "on-error-container": "#93000a",
        "secondary-container": "#57dffe",
        "inverse-surface": "#293040",
        "on-secondary-fixed-variant": "#004e5c",
        "outline": "#737686",
        "tertiary-fixed-dim": "#ffb596",
        "tertiary-container": "#bc4800",
        "on-primary-fixed": "#00174b",
        "brand-dark": "#0B1220",
        "brand-cyan": "#06B6D4"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "base": "4px",
        "xs": "clamp(8px, 0.6vw, 16px)",
        "sm": "clamp(16px, 1.25vw, 32px)",
        "md": "clamp(24px, 1.8vw, 48px)",
        "gutter": "clamp(24px, 2.5vw, 64px)",
        "lg": "clamp(48px, 3.75vw, 96px)",
        "xl": "clamp(80px, 6.25vw, 160px)",
        "2xl": "clamp(120px, 9.3vw, 240px)",
        "3xl": "clamp(160px, 12.5vw, 320px)",
        "margin-mobile": "16px",
        "container-max": "clamp(1280px, 85vw, 2560px)"
      },
      fontFamily: {
        "h1": ["Inter", "sans-serif"],
        "h2": ["Inter", "sans-serif"],
        "h3": ["Inter", "sans-serif"],
        "h4": ["Inter", "sans-serif"],
        "data-display": ["Inter", "sans-serif"],
        "h1-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "small": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      fontSize: {
        "h1": ["clamp(48px, 4vw, 72px)", { "lineHeight": "1.05", "letterSpacing": "-0.04em", "fontWeight": "700" }],
        "h2": ["clamp(36px, 3vw, 56px)", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "h3": ["clamp(24px, 2vw, 40px)", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "h4": ["clamp(18px, 1.5vw, 28px)", { "lineHeight": "1.3", "fontWeight": "500" }],
        "data-display": ["clamp(32px, 2.5vw, 64px)", { "lineHeight": "1.0", "fontWeight": "500" }],
        "h1-mobile": ["clamp(40px, 5vw, 56px)", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["clamp(18px, 1vw, 24px)", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body": ["clamp(16px, 1vw, 18px)", { "lineHeight": "1.6", "fontWeight": "400" }],
        "small": ["clamp(14px, 1vw, 16px)", { "lineHeight": "1.5", "fontWeight": "500" }],
        "label": ["clamp(12px, 0.8vw, 14px)", { "lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    }
  }
};
